FORMAT: 1A
HOST: giv-project7.uni-muenster.de:5000/api

# Smart Trash Bins


##### HOST
`http://giv-project7.uni-muenster.de:5000/api`

##### Status-Codes

| Code | Meaning |
|------|---------|
| `200` | Request successful |
| `201` | Created |
| `204` | No Content |
| `404` | Not found |
| `500` | Internal Server Error |
| `501` | Not implemented |



# Data Structures

## Trash Bin (object)
+ description: `Eingang des GEO1` (string, required) - Description of the location
+ filling_height: `60` (number, required) - Filling height `>= 0` of the trash bin, which is the height in Centimeter between the bottom and the ultra sonic sensor.
+ capacity: `60` (number, required) - Capacity `>= 0` in Liter of the trash bin
+ lng: `51.969148` (number, required) - Longitude value
+ lat: `7.595934` (number, required) - Latitude value

## Measurement (object)
+ trash_bin_id: `1` (number, required) - Id of a trash bin
+ measured_distance: `10` (number, required) - Distance `>= 0` in Centimeter, measured from the ultra sonic sensor to the ground, which decreases, when rubbish is inside
+ measured_filling_height `50` (number, required) - Distance `>= 0` in Centimeter, calculated by the filling height of the trash bin and the measured distance from the ultra sonic sensor: `filling_height - measured_distance`




## Trash Bin ::Arrays [/trash_bins{?lat,lng,latest_measurement}]


### List All Trash Bins [GET]

a) Without the parameters `?lng=51.969037&lat=7.603001`, the following attributes are not contained in the response:

* `distance` 
* `distance_unit`

b) Without the parameter `?latest_measurement=true`, the following attributes are not contained in the response:

* `timestamp` 
* `measured_distance` 
* `measured_distance_unit` 
* `measured_filling_height`
* `measured_filling_height_unit`

+ Parameters
    + lat: `51.969037` (optional) - Latitude value of the User
    + lng: `7.603001` (optional) - Longitude value of the User
    + latest_measurement: `true` (optional) - Latest measurement of a trash bin
    
+ Response 200 (application/json)

        [
            {
                "trash_bin_id": 2,
                "created": "2016-08-17T12:51:56.352Z",
                "updated": "2016-08-17T12:51:56.352Z",
                "description": "Bushaltestelle",
                "filling_height": 60,
                "filling_height_unit": "CENTIMETER",
                "capacity": 60,
                "capacity_unit": "LITER",
                "lng": 7.59676,
                "lat": 51.969357,
                "distance": 430.38893844,
                "distance_unit": "METER",
                "timestamp": "2016-08-17T12:51:56.352Z",
                "measured_distance": 40,
                "measured_distance_unit": "CENTIMETER",
                "measured_filling_height": 20,
                "measured_filling_height_unit": "CENTIMETER"
            }, {
                "trash_bin_id": 3,
                "created": "2016-08-17T12:51:56.352Z",
                "updated": "2016-08-17T12:51:56.352Z",
                "description": "Correnstraße",
                "filling_height": 60,
                "filling_height_unit": "CENTIMETER",
                "capacity": 60,
                "capacity_unit": "LITER",
                "lng": 7.596855,
                "lat": 51.971076,
                "distance": 479.45112773,
                "distance_unit": "METER",
                "timestamp": "2016-08-17T12:51:56.352Z",
                "measured_distance": 60,
                "measured_distance_unit": "CENTIMETER",
                "measured_filling_height": 0,
                "measured_filling_height_unit": "CENTIMETER"
            }, {
                "trash_bin_id": 1,
                "created": "2016-08-17T12:51:56.352Z",
                "updated": "2016-08-17T12:51:56.352Z",
                "description": "GEO1",
                "filling_height": 60,
                "filling_height_unit": "CENTIMETER",
                "capacity": 60,
                "capacity_unit": "LITER",
                "lng": 7.595934,
                "lat": 51.969148,
                "distance": 485.83873096,
                "distance_unit": "METER",
                "timestamp": "2016-08-17T12:51:56.352Z",
                "measured_distance": 20,
                "measured_distance_unit": "CENTIMETER",
                "measured_filling_height": 40,
                "measured_filling_height_unit": "CENTIMETER"
            }
        ]

### Create a new Trash Bin [POST]

+ Request (application/json)

        {
            "description": "Eingang Fachhochschule",
            "filling_height": 60,
            "capacity": 60,
            "lng": 7.595624,
            "lat": 51.968526
        }

+ Response 201 (application/json)

    + Body

            {
                "trash_bin_id": 4,
                "created": "2016-08-17T12:51:56.352Z",
                "updated": "2016-08-17T12:51:56.352Z",
                "description": "Eingang Fachhochschule",
                "filling_height": 60,
                "filling_height_unit": "CENTIMETER",
                "capacity": 60,
                "capacity_unit": "LITER",
                "lng": 7.595624,
                "lat": 51.968526
            }
            
            
## Trash Bin ::Object [/trash_bins/{trash_bin_id}{?latest_measurement}]

### Retrieve a Trash Bin [GET]

Without the parameter `?latest_measurement=true`, the following attributes are not contained in the response: 

* `timestamp` 
* `measured_distance` 
* `measured_distance_unit` 
* `measured_filling_height`
* `measured_filling_height_unit`


+ Parameters

    + trash\_bin\_id: `1` (required) - Id of a trash bin
    + latest\_measurement: `true` (optional) - Latest measurement of a trash bin

+ Response 200 (application/json)

    + Body
            
            {
                "trash_bin_id": 1,
                "created": "2016-08-17T12:51:56.352Z",
                "updated": "2016-08-17T12:51:56.352Z",
                "description": "GEO1",
                "filling_height": 60,
                "filling_height_unit": "CENTIMETER",
                "capacity": 60,
                "capacity_unit": "LITER",
                "lng": 7.595934,
                "lat": 51.969148,
                "timestamp": "2016-08-17T12:51:56.352Z",
                "measured_distance": 20,
                "measured_distance_unit": "CENTIMETER",
                "measured_filling_height": 40,
                "measured_filling_height_unit": "CENTIMETER"
            }
            
### Edit a Trash Bin [PUT]

+ Parameters

    + trash\_bin\_id: `1` (required) - Id of a trash bin

+ Request

    + Attributes (Trash Bin)
    
+ Response 200 (application/json)

    + Body
            
            {
                "trash_bin_id": 1,
                "created": "2016-08-17T12:51:56.352Z",
                "updated": "2016-08-17T12:51:56.352Z",
                "description": "GEO1",
                "filling_height": 60,
                "filling_height_unit": "CENTIMETER",
                "capacity": 60,
                "capacity_unit": "LITER",
                "lng": 7.595934,
                "lat": 51.969148,
                "timestamp": "2016-08-17T12:51:56.352Z",
                "measured_distance": 20,
                "measured_distance_unit": "CENTIMETER",
                "measured_filling_height": 40,
                "measured_filling_height_unit": "CENTIMETER"
            }

### Delete a Trash Bin [DELETE]

+ Parameters

    + trash\_bin\_id: `1` (required) - Id of a trash bin
    
+ Response 204



## Measurements ::Array [/trash_bins/{trash_bin_id}/measurements]

### List all Measurements of a Trash Bin [GET]

+ Parameters

    + trash\_bin\_id: `1` (required) - Id of a trash bin
    
+ Response 200 (application/json)

        [
                {
                    "measurement_id": 1,
                    "timestamp": "2016-08-17T12:51:56.352Z",
                    "measured_distance": 20,
                    "measured_distance_unit": "CENTIMETER",
                    "measured_filling_height": 40,
                    "measured_filling_height_unit": "CENTIMETER"
                }, {
                    "measurement_id": 2,
                    "timestamp": "2016-08-17T12:51:56.352Z",
                    "measured_distance": 30,
                    "measured_distance_unit": "CENTIMETER",
                    "measured_filling_height": 50,
                    "measured_filling_height_unit": "CENTIMETER"
                }, {
                    "measurement_id": 3,
                    "timestamp": "2016-08-17T12:51:56.352Z",
                    "measured_distance": 40,
                    "measured_distance_unit": "CENTIMETER",
                    "measured_filling_height": 20,
                    "measured_filling_height_unit": "CENTIMETER"
                }, {
                    "measurement_id": 4,
                    "timestamp": "2016-08-17T12:51:56.352Z",
                    "measured_distance": 50,
                    "measured_distance_unit": "CENTIMETER",
                    "measured_filling_height": 10,
                    "measured_filling_height_unit": "CENTIMETER"
                }
            ]


### Create a new Measurement for a Trash Bin [POST]

+ Parameters

    + trash\_bin\_id: `1` (required) - Id of a trash bin

+ Request

    + Attributes (Measurement)

+ Response 200 (application/json)

    + Body
            
            {
                "measurement_id": 5,
                "timestamp": "2016-08-17T12:51:56.352Z",
                "measured_distance": 10,
                "measured_distance_unit": "CENTIMETER",
                "measured_filling_height": 50,
                "measured_filling_height_unit": "CENTIMETER"
            }

### Delete all Measurements of a Trash Bin [DELETE]

+ Parameters

    + trash\_bin\_id: `1` (required) - Id of a trash bin
    
+ Response 204